changelog:
  categories:
    - title: Breaking Changes ⚠️
      labels:
        - breaking-change
    - title: New Features 🎉
      labels:
        - enhancement
    - title: Bug Fixes 🐛
      labels:
        - bug
        - hotfix
    - title: Other Changes
      labels:
        - "*"
